require 'config.globals'
require 'config.options'
require 'config.keymaps'
require 'config.statusline'
require 'config.autocmds'
require 'config.lazy'
require 'config.neovide'
require 'config.highlights'
