theme = "base16_transparent"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"
statusline.left = ["mode", "file-name", "read-only-indicator"]
statusline.right = ["version-control", "spacer", "diagnostics", "file-type", "position"]
cursor-shape.insert = "bar"
indent-guides.render = true

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
V = ["extend_line_below", "select_mode"]
